CREATE TABLE notification_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT uq_notification_preference_user_channel UNIQUE (user_id, channel),
    CONSTRAINT ck_notification_preference_channel CHECK (channel IN ('EMAIL', 'SMS', 'PUSH'))
);